export const IPC_CHANNELS = {
  LAUNCH_GAME: 'launch-game',
  VERSIONS_UPDATED: 'versions-updated',
  ALL_VERSION_INFO: 'request-version-information',
  SET_SELECTED_VERSION: 'set-selected-version',
  GET_SELECTED_VERSION: 'get-selected-version',
  CHECK_VERSION_INSTALLED: 'check-version-installed',
  SELECT_INSTALL_DIRECTORY: 'select-install-directory',
  DOWNLOAD_VERSION: 'download-version',
  DOWNLOAD_STATUS: 'download-status',
  DOWNLOAD_PROGRESS: 'download-progress',
  GET_DIRECTORIES: 'get-directories',
  PLAY_SOUND: 'play-sound',
  GET_URLS: 'get-urls',
  OPEN_DIRECTORY_DIALOG: 'open-directory-dialog',
  DIRECTORY_SELECTED: 'directory-selected',
  GET_SETTINGS: 'get-settings',
  SET_SETTINGS: 'set-settings',
} as const;
