name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.2'
          cache: 'pnpm'
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint
      - name: Run tests
        run: pnpm test
      - name: Build Electron app
        run: pnpm run make
